apiVersion: v1
kind: Secret
metadata:
  name: {{ include "worldcup.name" . }}-app
  labels: {{- include "worldcup.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_HOST: {{ include "worldcup.name" . }}-db
  DB_PORT: "5432"
  DB_USER: {{ .Values.db.user | quote }}
  DB_PASSWORD: {{ .Values.db.password | quote }}
  DB_NAME: {{ .Values.db.name | quote }}
