apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "worldcup.name" . }}-app
  labels: {{- include "worldcup.labels" . | nindent 4 }}
  {{- if .Values.ingress.tls.enabled }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.clusterIssuer }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "worldcup.name" . }}-app
                port:
                  number: 80
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: {{ include "worldcup.name" . }}-tls
  {{- end }}
