apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "worldcup.name" . }}-app
  labels: {{- include "worldcup.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels: {{- include "worldcup.appSelector" . | nindent 6 }}
