{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "worldcup.name" . }}-app
  labels:
    {{- include "worldcup.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: worldcup
      app.kubernetes.io/component: app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
