apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "worldcup.name" . }}-report
  labels: {{- include "worldcup.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          containers:
            - name: report
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["node", "jobs/report.js"]
              envFrom:
                - secretRef:
                    name: {{ include "worldcup.name" . }}-app
