apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "worldcup.name" . }}-db
  labels: {{- include "worldcup.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "worldcup.name" . }}-db
  replicas: 1
  selector:
    matchLabels: {{- include "worldcup.dbSelector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "worldcup.labels" . | nindent 8 }}
        {{- include "worldcup.dbSelector" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.db.image }}
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: {{ include "worldcup.name" . }}-db
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 20
            periodSeconds: 10
          resources: {{- toYaml .Values.db.resources | nindent 12 }}
      volumes:
        - name: initdb
          configMap:
            name: {{ include "worldcup.name" . }}-initdb
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.db.storage }}
