apiVersion: v1
kind: Service
metadata:
  name: {{ include "worldcup.name" . }}-db
  labels: {{- include "worldcup.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector: {{- include "worldcup.dbSelector" . | nindent 4 }}
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
